const data = {
  products: [
    {
      name: 'Looki 001',
      slug: 'looki-001',
      category: 'Looki',
      image: '/images/looki/looki-001.png',
      price: 200,
      counInStock: 6,
      brand: 'Nft',
      rating: 5,
      numReviews: 10,
      description: 'high quanlity',
    },
    {
      name: 'Looki 002',
      slug: 'looki-002',
      category: 'Looki',
      image: '/images/looki/looki-002.png',
      price: 200,
      counInStock: 6,
      brand: 'Nft',
      rating: 5,
      numReviews: 10,
      description: 'high quanlity',
    },
    {
      name: 'Looki 003',
      slug: 'looki-003',
      category: 'Looki',
      image: '/images/looki/looki-003.png',
      price: 200,
      counInStock: 6,
      brand: 'Nft',
      rating: 5,
      numReviews: 10,
      description: 'high quanlity',
    },
    {
      name: 'Looki 004',
      slug: 'looki-004',
      category: 'Looki',
      image: '/images/looki/looki-004.png',
      price: 200,
      counInStock: 6,
      brand: 'Nft',
      rating: 5,
      numReviews: 10,
      description: 'high quanlity',
    },
    {
      name: 'Looki 005',
      slug: 'looki-005',
      category: 'Looki',
      image: '/images/looki/looki-005.png',
      price: 200,
      counInStock: 6,
      brand: 'Nft',
      rating: 5,
      numReviews: 10,
      description: 'high quanlity',
    },
    {
      name: 'Looki 006',
      slug: 'looki-006',
      category: 'Looki',
      image: '/images/looki/looki-006.png',
      price: 200,
      counInStock: 6,
      brand: 'Nft',
      rating: 5,
      numReviews: 10,
      description: 'high quanlity',
    },
  ],
};

export default data;
